# Generated by Django 5.2 on 2025-04-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_contact_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Invite Message',
                'verbose_name_plural': 'Invite Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
