# Generated by Django 5.2 on 2025-04-23 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_invitemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitemessage',
            name='link',
            field=models.URLField(default='https://play.google.com/store/apps/details?id=com.example.app', help_text='App store or download link', max_length=500),
        ),
    ]
