# Generated by Django 5.2 on 2025-04-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_invitemessage_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitemessage',
            name='link',
            field=models.URLField(help_text='App store or download link', max_length=500),
        ),
    ]
