# Generated by Django 5.2 on 2025-04-24 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='category',
            field=models.ForeignKey(blank=True, help_text="Category to show when clicking the 'Show Now' button", null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.category'),
        ),
    ]
